version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "01:37"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
